# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  # This job is used as a template for each Node.js version.
  build-node-common:
    &common-build # This property is overridden by each job but is set because it's mandatory.
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn ci

  build-node-8:
    <<: *common-build
    docker:
      - image: circleci/node:8

  build-node-10:
    <<: *common-build
    docker:
      - image: circleci/node:10

  build-node-11:
    <<: *common-build
    docker:
      - image: circleci/node:11

  build-node-12:
    <<: *common-build
    docker:
      - image: circleci/node:12

workflows:
  version: 2
  build:
    jobs:
      - build-node-8
      - build-node-10
      - build-node-11
      - build-node-12
